//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShiraDK
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuyingTickets
    {
        public int Number { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public int SalesmanID { get; set; }
        public Nullable<int> BuyerID { get; set; }
        public int EventID { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual Events Events { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
