//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShiraDK
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=BDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        private static DBEntities _context;
        public static DBEntities GetContext()
        {
            if (_context == null)
                _context = new DBEntities();
            return _context;
        }
        public virtual DbSet<BuyingTickets> BuyingTickets { get; set; }
        public virtual DbSet<Events> Events { get; set; }
        public virtual DbSet<Items> Items { get; set; }
        public virtual DbSet<ItemsForEvents> ItemsForEvents { get; set; }
        public virtual DbSet<Organizers> Organizers { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<WareHouse> WareHouse { get; set; }
    }
}
